// General Knowledge TZ q213-q222
export const generalQuestions = [
  { id: 'q213', category: 'General Knowledge TZ', question: 'Bendera ya Tanzania ina rangi ngapi?', question_en: 'How many colours does the Tanzanian flag have?', options: ['4', '3', '2', '5'], options_en: ['4', '3', '2', '5'], answer: '4', answer_en: '4', explanation: 'Bendera ya Tanzania ina rangi nne: kijani, njano, nyeusi, na bluu.', explanation_en: "Tanzania's flag has four colours: green, yellow, black, and blue.", difficulty: 'easy' },
  { id: 'q214', category: 'General Knowledge TZ', question: 'Ziwa gani ni kubwa zaidi barani Afrika?', question_en: 'Which lake is the largest in Africa?', options: ['Ziwa Victoria', 'Ziwa Tanganyika', 'Ziwa Malawi', 'Ziwa Turkana'], options_en: ['Lake Victoria', 'Lake Tanganyika', 'Lake Malawi', 'Lake Turkana'], answer: 'Ziwa Victoria', answer_en: 'Lake Victoria', explanation: 'Ziwa Victoria ni ziwa kubwa zaidi barani Afrika, likiwa kati ya Tanzania, Kenya, na Uganda.', explanation_en: 'Lake Victoria is the largest lake in Africa, shared by Tanzania, Kenya, and Uganda.', difficulty: 'easy' },
  { id: 'q215', category: 'General Knowledge TZ', question: 'Kiswahili ni lugha rasmi ya nchi zipi Afrika Mashariki?', question_en: 'Swahili is an official language of which East African countries?', options: ['Tanzania, Kenya, Uganda, Rwanda', 'Tanzania na Kenya tu', 'Tanzania peke yake', 'Tanzania, Msumbiji, DRC'], options_en: ['Tanzania, Kenya, Uganda, Rwanda', 'Tanzania and Kenya only', 'Tanzania only', 'Tanzania, Mozambique, DRC'], answer: 'Tanzania, Kenya, Uganda, Rwanda', answer_en: 'Tanzania, Kenya, Uganda, Rwanda', explanation: 'Kiswahili ni lugha rasmi ya Tanzania, Kenya, Uganda, na Rwanda ndani ya jumuiya ya Afrika Mashariki.', explanation_en: 'Swahili is an official language of Tanzania, Kenya, Uganda, and Rwanda within the East African Community.', difficulty: 'hard' },
  { id: 'q216', category: 'General Knowledge TZ', question: 'Tanzania ina watu wangapi takriban (sensa ya 2022)?', question_en: "What is Tanzania's approximate population (2022 census)?", options: ['Zaidi ya milioni 61', 'Milioni 40', 'Milioni 80', 'Milioni 30'], options_en: ['Over 61 million', '40 million', '80 million', '30 million'], answer: 'Zaidi ya milioni 61', answer_en: 'Over 61 million', explanation: 'Kulingana na sensa ya 2022, Tanzania ina watu zaidi ya milioni 61.', explanation_en: 'According to the 2022 census, Tanzania has a population of over 61 million.', difficulty: 'medium', timeSensitive: true, reviewAfter: '2030-12-31', reviewReason: 'Population grows with each census; next census expected around 2032.', sourceNote: 'Tanzania National Bureau of Statistics 2022 census result.', sourceUrl: 'https://www.nbs.go.tz' },
  { id: 'q217', category: 'General Knowledge TZ', question: 'Sarafu ya Tanzania inaitwa nini?', question_en: "What is Tanzania's currency called?", options: ['Shilingi ya Tanzania', 'Dola ya Tanzania', 'Frank ya Tanzania', 'Pound ya Tanzania'], options_en: ['Tanzanian Shilling', 'Tanzanian Dollar', 'Tanzanian Franc', 'Tanzanian Pound'], answer: 'Shilingi ya Tanzania', answer_en: 'Tanzanian Shilling', explanation: 'Sarafu rasmi ya Tanzania ni Shilingi ya Tanzania (TZS).', explanation_en: "Tanzania's official currency is the Tanzanian Shilling (TZS).", difficulty: 'easy' },
  { id: 'q218', category: 'General Knowledge TZ', question: 'Katiba ya Tanzania ya sasa ilipitishwa mwaka gani?', question_en: "In which year was Tanzania's current constitution adopted?", options: ['1977', '1964', '1961', '1992'], options_en: ['1977', '1964', '1961', '1992'], answer: '1977', answer_en: '1977', explanation: 'Katiba ya Tanzania ya sasa ilipitishwa mwaka 1977, ingawa imefanyiwa marekebisho mara kadhaa.', explanation_en: "Tanzania's current constitution was adopted in 1977, though it has been amended several times.", difficulty: 'hard' },
  { id: 'q219', category: 'General Knowledge TZ', question: 'Nchi gani zinapakana na Tanzania upande wa kaskazini?', question_en: 'Which countries border Tanzania to the north?', options: ['Kenya na Uganda', 'Rwanda na Burundi', 'Msumbiji na Malawi', 'DRC na Zambia'], options_en: ['Kenya and Uganda', 'Rwanda and Burundi', 'Mozambique and Malawi', 'DRC and Zambia'], answer: 'Kenya na Uganda', answer_en: 'Kenya and Uganda', explanation: 'Kenya na Uganda zinapakana na Tanzania upande wa kaskazini.', explanation_en: 'Kenya and Uganda border Tanzania to the north.', difficulty: 'easy' },
  { id: 'q220', category: 'General Knowledge TZ', question: 'Lugha ya taifa ya Tanzania ni ipi?', question_en: "What is Tanzania's national language?", options: ['Kiswahili', 'Kiingereza', 'Kiarabu', 'Kichagga'], options_en: ['Swahili', 'English', 'Arabic', 'Chagga'], answer: 'Kiswahili', answer_en: 'Swahili', explanation: 'Kiswahili ni lugha ya taifa na lugha rasmi ya Tanzania, inayozungumzwa na watu wote.', explanation_en: 'Swahili is the national and official language of Tanzania, spoken by everyone.', difficulty: 'easy' },
  { id: 'q221', category: 'General Knowledge TZ', question: 'Milima ya Usambara ipo mkoa gani?', question_en: 'The Usambara Mountains are in which region?', options: ['Tanga', 'Kilimanjaro', 'Mbeya', 'Dodoma'], options_en: ['Tanga', 'Kilimanjaro', 'Mbeya', 'Dodoma'], answer: 'Tanga', answer_en: 'Tanga', explanation: 'Milima ya Usambara ipo mkoa wa Tanga mashariki mwa Tanzania, ikijulikana kwa mazingira mazuri.', explanation_en: 'The Usambara Mountains are in Tanga Region in eastern Tanzania, known for beautiful scenery.', difficulty: 'medium' },
  { id: 'q222', category: 'General Knowledge TZ', question: 'Zanzibar ina uhuru gani ndani ya Jamhuri ya Muungano wa Tanzania?', question_en: 'What autonomy does Zanzibar have within the United Republic of Tanzania?', options: ['Serikali yake ya ndani inayosimamiwa na Rais wa Zanzibar', 'Uhuru kamili wa serikali', 'Mkoa tu bila mamlaka ya ziada', 'Inategemea kabisa serikali kuu'], options_en: ['Own internal government led by Zanzibar President', 'Full independence', 'A region with no extra authority', 'Fully dependent on central government'], answer: 'Serikali yake ya ndani inayosimamiwa na Rais wa Zanzibar', answer_en: 'Own internal government led by Zanzibar President', explanation: 'Zanzibar ina serikali yake ya ndani (SMZ) inayosimamiwa na Rais wa Zanzibar.', explanation_en: 'Zanzibar has its own internal government (SMZ) led by the Zanzibar President, while union matters are shared.', difficulty: 'hard' },
];
