// Mikoa ya Tanzania batch 5 — q471–q474
export const mikoaE = [
  {
    id: "q471",
    category: "Mikoa ya Tanzania",
    question: "Mkoa gani wa Tanzania unajulikana kwa mazao ya parachichi (avocado)?",
    question_en: "Which Tanzanian region is known for avocado production?",
    options: ["Kilimanjaro", "Mwanza", "Lindi", "Shinyanga"],
    options_en: ["Kilimanjaro", "Mwanza", "Lindi", "Shinyanga"],
    answer: "Kilimanjaro",
    answer_en: "Kilimanjaro",
    explanation: "Mkoa wa Kilimanjaro, hasa maeneo ya chini ya mlima, unajulikana kwa uzalishaji wa parachichi ya ubora wa juu ambayo husafirishwa nje ya nchi.",
    explanation_en: "Kilimanjaro Region, especially the lower mountain slopes, is known for producing high-quality avocados that are exported.",
    difficulty: "medium",
  },
  {
    id: "q472",
    category: "Mikoa ya Tanzania",
    question: "Mji mkuu wa mkoa wa Geita ni upi?",
    question_en: "What is the regional capital of Geita Region?",
    options: ["Geita", "Bukoba", "Musoma", "Biharamulo"],
    options_en: ["Geita", "Bukoba", "Musoma", "Biharamulo"],
    answer: "Geita",
    answer_en: "Geita",
    explanation: "Geita ndiyo mji mkuu wa mkoa wa Geita, ulioundwa mwaka 2012 ukitenganishwa na mkoa wa Mwanza.",
    explanation_en: "Geita is the regional capital of Geita Region, which was created in 2012 when it was carved out of Mwanza Region.",
    difficulty: "medium",
    sourceNote: "Geita Region was established in 2012 by presidential decree.",
    sourceUrl: "https://www.parliament.go.tz",
  },
  {
    id: "q473",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Kagera unapakana na nchi zipi?",
    question_en: "Kagera Region borders which countries?",
    options: ["Uganda, Rwanda na Burundi", "Kenya na Uganda", "Msumbiji na Malawi", "Zambia na DRC"],
    options_en: ["Uganda, Rwanda and Burundi", "Kenya and Uganda", "Mozambique and Malawi", "Zambia and DRC"],
    answer: "Uganda, Rwanda na Burundi",
    answer_en: "Uganda, Rwanda and Burundi",
    explanation: "Mkoa wa Kagera kaskazini magharibi mwa Tanzania unapakana na Uganda kaskazini, Rwanda na Burundi magharibi.",
    explanation_en: "Kagera Region in north-western Tanzania borders Uganda to the north, Rwanda and Burundi to the west.",
    difficulty: "medium",
  },
  {
    id: "q474",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Njombe unajulikana kwa zao gani la chakula?",
    question_en: "Njombe Region is known for which food crop?",
    options: ["Viazi (Potatoes)", "Kahawa (Coffee)", "Pamba (Cotton)", "Mahindi (Maize)"],
    options_en: ["Potatoes", "Coffee", "Cotton", "Maize"],
    answer: "Viazi (Potatoes)",
    answer_en: "Potatoes",
    explanation: "Mkoa wa Njombe, wenye hali ya hewa baridi, unajulikana kwa uzalishaji mkubwa wa viazi Tanzania.",
    explanation_en: "Njombe Region, with its cool highland climate, is known for large-scale potato production in Tanzania.",
    difficulty: "medium",
  },
];
