// Mitaa ya Dar q183-q192
export const mitaaQuestions = [
  { id: 'q183', category: 'Mitaa ya Dar', question: 'Mtaa wa Magomeni uko wilaya gani Dar es Salaam?', question_en: 'Magomeni neighbourhood is in which district of Dar es Salaam?', options: ['Kinondoni', 'Ilala', 'Temeke', 'Ubungo'], options_en: ['Kinondoni', 'Ilala', 'Temeke', 'Ubungo'], answer: 'Kinondoni', answer_en: 'Kinondoni', explanation: 'Magomeni ni mtaa uliopo wilaya ya Kinondoni, Dar es Salaam.', explanation_en: 'Magomeni is a neighbourhood in Kinondoni District, Dar es Salaam.', difficulty: 'medium' },
  { id: 'q184', category: 'Mitaa ya Dar', question: 'Bandari Kuu ya Tanzania ipo eneo gani Dar es Salaam?', question_en: "Tanzania's main port is in which area of Dar es Salaam?", options: ['Kurasini / Gerezani', 'Kariakoo', 'Masaki', 'Ubungo'], options_en: ['Kurasini / Gerezani', 'Kariakoo', 'Masaki', 'Ubungo'], answer: 'Kurasini / Gerezani', answer_en: 'Kurasini / Gerezani', explanation: 'Bandari Kuu ya Dar es Salaam ipo eneo la Kurasini na Gerezani.', explanation_en: "Dar es Salaam's main port is in the Kurasini and Gerezani area.", difficulty: 'medium' },
  { id: 'q185', category: 'Mitaa ya Dar', question: 'Temeke iko sehemu gani ya Dar es Salaam?', question_en: 'Temeke is in which part of Dar es Salaam?', options: ['Kusini', 'Kaskazini', 'Mashariki', 'Magharibi'], options_en: ['South', 'North', 'East', 'West'], answer: 'Kusini', answer_en: 'South', explanation: 'Temeke ni wilaya ya kusini mwa Dar es Salaam, yenye viwanda vingi.', explanation_en: 'Temeke is the southern district of Dar es Salaam, with many industrial facilities.', difficulty: 'medium' },
  { id: 'q186', category: 'Mitaa ya Dar', question: 'Posta Kuu ya Dar es Salaam ipo eneo gani?', question_en: "Dar es Salaam's General Post Office is in which area?", options: ['Katikati ya jiji (CBD)', 'Kariakoo', 'Kinondoni', 'Temeke'], options_en: ['City Centre (CBD)', 'Kariakoo', 'Kinondoni', 'Temeke'], answer: 'Katikati ya jiji (CBD)', answer_en: 'City Centre (CBD)', explanation: 'Posta Kuu ipo katikati ya jiji (CBD) katika eneo linaloitwa "Posta".', explanation_en: 'The General Post Office is in the city centre (CBD) in an area nicknamed "Posta".', difficulty: 'easy' },
  { id: 'q187', category: 'Mitaa ya Dar', question: 'Chuo Kikuu cha Dar es Salaam (UDSM) ipo eneo gani?', question_en: 'University of Dar es Salaam (UDSM) is located in which area?', options: ['Observation Hill karibu na Ubungo', 'Kariakoo', 'Temeke', 'Msasani'], options_en: ['Observation Hill near Ubungo', 'Kariakoo', 'Temeke', 'Msasani'], answer: 'Observation Hill karibu na Ubungo', answer_en: 'Observation Hill near Ubungo', explanation: 'UDSM ipo katika kilima kinachojulikana kama Observation Hill, karibu na Ubungo.', explanation_en: 'UDSM is on the hill known as Observation Hill, near the Ubungo area.', difficulty: 'medium' },
  { id: 'q188', category: 'Mitaa ya Dar', question: 'Msasani Peninsula inajulikana zaidi kwa nini?', question_en: 'Msasani Peninsula is best known for what?', options: ['Mbuga za starehe na jumuiya ya wageni wa kigeni', 'Viwanda vikubwa', 'Masoko ya samaki', 'Maegesho ya meli kubwa'], options_en: ['Leisure spots and expat community', 'Large industries', 'Fish markets', 'Large ship docks'], answer: 'Mbuga za starehe na jumuiya ya wageni wa kigeni', answer_en: 'Leisure spots and expat community', explanation: 'Msasani inajulikana kwa mikahawa, baa, na jumuiya kubwa ya wajenzi wa kigeni.', explanation_en: 'Msasani is known for restaurants, bars, and a large expatriate community.', difficulty: 'medium' },
  { id: 'q189', category: 'Mitaa ya Dar', question: 'Soko la Kariakoo linajulikana kwa bidhaa gani zaidi?', question_en: 'Kariakoo market is best known for what goods?', options: ['Bidhaa mbalimbali za jumla', 'Nguo za bei ghali', 'Samaki wa bahari tu', 'Magari ya pili'], options_en: ['Wholesale goods of all types', 'Expensive clothes', 'Sea fish only', 'Used cars'], answer: 'Bidhaa mbalimbali za jumla', answer_en: 'Wholesale goods of all types', explanation: 'Kariakoo ni mojawapo ya masoko makubwa zaidi Afrika Mashariki, yakiuza bidhaa kwa jumla.', explanation_en: "Kariakoo is one of East Africa's largest markets, selling wholesale goods of all types.", difficulty: 'easy' },
  { id: 'q190', category: 'Mitaa ya Dar', question: 'Ubungo Bus Terminal ni nini?', question_en: 'What is Ubungo Bus Terminal?', options: ['Kituo kikubwa cha mabasi ya safari za mbali', 'Hospitali ya serikali', 'Uwanja wa michezo', 'Kituo cha reli'], options_en: ['Major long-distance bus terminal', 'Government hospital', 'Sports ground', 'Railway station'], answer: 'Kituo kikubwa cha mabasi ya safari za mbali', answer_en: 'Major long-distance bus terminal', explanation: 'Ubungo ni kituo kikubwa cha mabasi ya safari za mbali nchini Tanzania.', explanation_en: 'Ubungo is the major long-distance bus terminal in Tanzania.', difficulty: 'easy' },
  { id: 'q191', category: 'Mitaa ya Dar', question: 'Mikocheni inajulikana zaidi kwa nini?', question_en: 'Mikocheni is best known for what?', options: ['Makazi ya tabaka la kati na juu', 'Viwanda vya chakula', 'Masoko ya mbogamboga', 'Maegesho ya boti'], options_en: ['Middle and upper-class residences', 'Food factories', 'Vegetable markets', 'Boat docks'], answer: 'Makazi ya tabaka la kati na juu', answer_en: 'Middle and upper-class residences', explanation: 'Mikocheni ni eneo la makazi mazuri la tabaka la kati na juu Dar es Salaam.', explanation_en: 'Mikocheni is an upscale residential area for the middle and upper classes in Dar es Salaam.', difficulty: 'medium' },
  { id: 'q192', category: 'Mitaa ya Dar', question: 'Mbagala iko wilaya gani Dar es Salaam?', question_en: 'Mbagala is in which district of Dar es Salaam?', options: ['Temeke', 'Kinondoni', 'Ilala', 'Ubungo'], options_en: ['Temeke', 'Kinondoni', 'Ilala', 'Ubungo'], answer: 'Temeke', answer_en: 'Temeke', explanation: 'Mbagala ni mtaa mkubwa katika wilaya ya Temeke, kusini mwa Dar es Salaam.', explanation_en: 'Mbagala is a large neighbourhood in Temeke District, southern Dar es Salaam.', difficulty: 'hard' },
];
