// Mitaa ya Dar batch 4 — q431–q438
export const mitaaD = [
  {
    id: "q431",
    category: "Mitaa ya Dar",
    question: "Mtaa wa Sinza uko wilaya gani ya Dar es Salaam?",
    question_en: "Sinza neighbourhood is in which district of Dar es Salaam?",
    options: ["Kinondoni", "Ilala", "Temeke", "Ubungo"],
    options_en: ["Kinondoni", "Ilala", "Temeke", "Ubungo"],
    answer: "Kinondoni",
    answer_en: "Kinondoni",
    explanation: "Sinza ni mtaa wa makazi uliopo wilaya ya Kinondoni, kaskazini ya mji wa Dar es Salaam.",
    explanation_en: "Sinza is a residential neighbourhood in Kinondoni District, in the northern part of Dar es Salaam.",
    difficulty: "easy",
  },
  {
    id: "q432",
    category: "Mitaa ya Dar",
    question: "Ghorofa ngapi ina jengo maarufu la 'PSPF Towers' Dar es Salaam?",
    question_en: "How many floors does the famous 'PSPF Towers' building have in Dar es Salaam?",
    options: ["35", "20", "50", "15"],
    options_en: ["35", "20", "50", "15"],
    answer: "35",
    answer_en: "35",
    explanation: "PSPF Twin Towers (jengo la ghorofa 35) ni miongoni mwa majengo mrefu zaidi Dar es Salaam na yenye umuhimu mkubwa kibiashara.",
    explanation_en: "PSPF Twin Towers (35 floors each) are among the tallest buildings in Dar es Salaam and major commercial landmarks.",
    difficulty: "hard",
    sourceNote: "PSPF Twin Towers are 35-storey buildings completed in Dar es Salaam's CBD.",
    sourceUrl: "https://www.pspf.go.tz",
  },
  {
    id: "q433",
    category: "Mitaa ya Dar",
    question: "Mkondo wa maji unaopita Dar es Salaam kutoka kaskazini hadi baharini unaitwa nini?",
    question_en: "What is the creek called that flows through Dar es Salaam from north to the sea?",
    options: ["Mto Msimbazi", "Mto Ruvu", "Mto Wami", "Mto Pangani"],
    options_en: ["Msimbazi River", "Ruvu River", "Wami River", "Pangani River"],
    answer: "Mto Msimbazi",
    answer_en: "Msimbazi River",
    explanation: "Mto Msimbazi unapita katikati ya Dar es Salaam, ukigawanya maeneo ya Kariakoo na Ilala, na mara nyingi husababisha mafuriko wakati wa mvua.",
    explanation_en: "The Msimbazi River flows through central Dar es Salaam, separating areas like Kariakoo and Ilala, and often causes flooding during heavy rains.",
    difficulty: "medium",
  },
  {
    id: "q434",
    category: "Mitaa ya Dar",
    question: "Hospitali ya taifa ya Tanzania inayoitwa 'Muhimbili' ipo mtaa gani?",
    question_en: "Tanzania's national hospital called 'Muhimbili' is in which neighbourhood?",
    options: ["Upanga", "Kariakoo", "Kinondoni", "Mwenge"],
    options_en: ["Upanga", "Kariakoo", "Kinondoni", "Mwenge"],
    answer: "Upanga",
    answer_en: "Upanga",
    explanation: "Hospitali ya Taifa ya Muhimbili (MNH) ipo eneo la Upanga, Dar es Salaam, na ni hospitali kubwa zaidi na ya rufaa Tanzania.",
    explanation_en: "Muhimbili National Hospital (MNH) is in the Upanga area of Dar es Salaam and is Tanzania's largest referral hospital.",
    difficulty: "medium",
  },
  {
    id: "q435",
    category: "Mitaa ya Dar",
    question: "Mtaa gani wa Dar es Salaam unajulikana kwa soko la magari ya pili (used cars)?",
    question_en: "Which Dar es Salaam neighbourhood is known for the second-hand car market?",
    options: ["Gongo la Mboto / Ukonga", "Kariakoo", "Mwenge", "Ubungo"],
    options_en: ["Gongo la Mboto / Ukonga", "Kariakoo", "Mwenge", "Ubungo"],
    answer: "Gongo la Mboto / Ukonga",
    answer_en: "Gongo la Mboto / Ukonga",
    explanation: "Eneo la Gongo la Mboto na Ukonga lina masoko maarufu ya magari ya pili (mitumba ya magari) Dar es Salaam.",
    explanation_en: "The Gongo la Mboto and Ukonga area has well-known second-hand car markets in Dar es Salaam.",
    difficulty: "medium",
  },
  {
    id: "q436",
    category: "Mitaa ya Dar",
    question: "Jengo la kwanza la ghorofa nyingi lijengwa Dar es Salaam lilikuwa lipi?",
    question_en: "What was the first multi-storey building constructed in Dar es Salaam?",
    options: ["NIC Investment House", "Askance Building", "Blue Pearl Hotel", "IPS Building"],
    options_en: ["NIC Investment House", "Askance Building", "Blue Pearl Hotel", "IPS Building"],
    answer: "NIC Investment House",
    answer_en: "NIC Investment House",
    explanation: "NIC Investment House (zamani Royal Insurance Building) ilikuwa miongoni mwa majengo ya kwanza ya ghorofa nyingi Dar es Salaam katika miaka ya 1960.",
    explanation_en: "NIC Investment House (formerly Royal Insurance Building) was among the first multi-storey buildings in Dar es Salaam in the 1960s.",
    difficulty: "hard",
  },
  {
    id: "q437",
    category: "Mitaa ya Dar",
    question: "Mtaa wa Posta uko eneo gani la Dar es Salaam?",
    question_en: "The Posta neighbourhood is in which area of Dar es Salaam?",
    options: ["Katikati ya mji (City Centre)", "Kinondoni", "Temeke", "Ubungo"],
    options_en: ["City Centre", "Kinondoni", "Temeke", "Ubungo"],
    answer: "Katikati ya mji (City Centre)",
    answer_en: "City Centre",
    explanation: "Posta ni eneo la katikati ya mji Dar es Salaam, linalopata jina lake kutoka Posta Kuu ya Tanzania iliyopo hapo.",
    explanation_en: "Posta is a city centre area in Dar es Salaam, named after the main Tanzania Post Office located there.",
    difficulty: "easy",
  },
  {
    id: "q438",
    category: "Mitaa ya Dar",
    question: "Daraja gani linaunganisha Dar es Salaam Bara na Kigamboni?",
    question_en: "Which bridge connects mainland Dar es Salaam to Kigamboni?",
    options: ["Daraja la Kigamboni", "Daraja la Msimbazi", "Daraja la Selander", "Daraja la Kariakoo"],
    options_en: ["Kigamboni Bridge", "Msimbazi Bridge", "Selander Bridge", "Kariakoo Bridge"],
    answer: "Daraja la Kigamboni",
    answer_en: "Kigamboni Bridge",
    explanation: "Daraja la Kigamboni lilijengwa na kufunguliwa mwaka 2016, likiunganisha eneo la Kigamboni na mji mkuu wa Dar es Salaam bila kivuko cha maji.",
    explanation_en: "Kigamboni Bridge was built and opened in 2016, connecting Kigamboni to the main Dar es Salaam city without needing a water ferry.",
    difficulty: "easy",
    sourceNote: "Kigamboni Bridge opened in 2016.",
    sourceUrl: "https://www.tanroads.go.tz",
  },
];
