// Mitaa ya Dar batch 2 — q271–q278
export const mitaaB = [
  {
    id: "q271",
    category: "Mitaa ya Dar",
    question: "Soko kubwa zaidi la bidhaa za jumla Dar es Salaam linaitwa nini?",
    question_en: "What is the name of the largest wholesale market in Dar es Salaam?",
    options: ["Kariakoo Market", "Ilala Market", "Kisutu Market", "Tandale Market"],
    options_en: ["Kariakoo Market", "Ilala Market", "Kisutu Market", "Tandale Market"],
    answer: "Kariakoo Market",
    answer_en: "Kariakoo Market",
    explanation: "Soko la Kariakoo ni soko kubwa zaidi na maarufu zaidi Dar es Salaam, linalohudumia wafanyabiashara wengi.",
    explanation_en: "Kariakoo Market is the largest and most famous market in Dar es Salaam, serving many traders.",
    difficulty: "easy",
  },
  {
    id: "q272",
    category: "Mitaa ya Dar",
    question: "Wilaya ya Temeke ipo sehemu gani ya Dar es Salaam?",
    question_en: "Temeke District is in which part of Dar es Salaam?",
    options: ["Kusini", "Kaskazini", "Mashariki", "Magharibi"],
    options_en: ["South", "North", "East", "West"],
    answer: "Kusini",
    answer_en: "South",
    explanation: "Wilaya ya Temeke ipo kusini mwa Dar es Salaam, na inajumuisha maeneo ya Chang'ombe, Mtoni, na Kigamboni.",
    explanation_en: "Temeke District is in the southern part of Dar es Salaam, encompassing areas including Chang'ombe, Mtoni, and Kigamboni.",
    difficulty: "medium",
  },
  {
    id: "q273",
    category: "Mitaa ya Dar",
    question: "Mtaa wa Oyster Bay unajulikana kwa nini?",
    question_en: "What is the Oyster Bay neighbourhood known for?",
    options: ["Makazi ya Mabalozi na wageni wa kimataifa", "Soko kubwa la samaki", "Viwanda vikubwa", "Bandari ya uvuvi"],
    options_en: ["Diplomatic residences and international guests", "Large fish market", "Major industries", "Fishing port"],
    answer: "Makazi ya Mabalozi na wageni wa kimataifa",
    answer_en: "Diplomatic residences and international guests",
    explanation: "Oyster Bay ni mtaa wa hali ya juu Dar es Salaam unaojulikana kwa makazi ya mabalozi na wageni wa kimataifa.",
    explanation_en: "Oyster Bay is an upmarket neighbourhood in Dar es Salaam known for diplomatic residences and international visitors.",
    difficulty: "medium",
  },
  {
    id: "q274",
    category: "Mitaa ya Dar",
    question: "Bandari ya Dar es Salaam ipo mtaa gani?",
    question_en: "Dar es Salaam port is located in which neighbourhood?",
    options: ["Kurasini", "Kariakoo", "Kinondoni", "Ubungo"],
    options_en: ["Kurasini", "Kariakoo", "Kinondoni", "Ubungo"],
    answer: "Kurasini",
    answer_en: "Kurasini",
    explanation: "Bandari ya Dar es Salaam ipo Kurasini, wilaya ya Temeke, na ni bandari kuu ya Tanzania.",
    explanation_en: "Dar es Salaam port is located in Kurasini, Temeke District, and is Tanzania's main port.",
    difficulty: "medium",
  },
  {
    id: "q275",
    category: "Mitaa ya Dar",
    question: "Chuo Kikuu cha Dar es Salaam (UDSM) kipo mtaa gani?",
    question_en: "The University of Dar es Salaam (UDSM) is located in which area?",
    options: ["Ubungo", "Kinondoni", "Ilala", "Temeke"],
    options_en: ["Ubungo", "Kinondoni", "Ilala", "Temeke"],
    answer: "Ubungo",
    answer_en: "Ubungo",
    explanation: "Chuo Kikuu cha Dar es Salaam kipo mlimani, eneo la Ubungo, na ni chuo kikuu kongwe zaidi Tanzania.",
    explanation_en: "The University of Dar es Salaam is located on the hill in Ubungo area and is Tanzania's oldest university.",
    difficulty: "medium",
  },
  {
    id: "q276",
    category: "Mitaa ya Dar",
    question: "Uwanja wa Ndege wa Julius Nyerere uko wilaya gani Dar es Salaam?",
    question_en: "Julius Nyerere International Airport is in which district of Dar es Salaam?",
    options: ["Ilala", "Temeke", "Kinondoni", "Ubungo"],
    options_en: ["Ilala", "Temeke", "Kinondoni", "Ubungo"],
    answer: "Ilala",
    answer_en: "Ilala",
    explanation: "Uwanja wa Ndege wa Julius Nyerere uko wilaya ya Ilala, na ni kiungo kikuu cha usafiri wa anga Tanzania.",
    explanation_en: "Julius Nyerere International Airport is in Ilala District and is Tanzania's main aviation hub.",
    difficulty: "medium",
  },
  {
    id: "q277",
    category: "Mitaa ya Dar",
    question: "Mtaa wa Msasani unajulikana kwa nini Dar es Salaam?",
    question_en: "What is the Msasani neighbourhood known for in Dar es Salaam?",
    options: ["Peninsula na maeneo ya burudani", "Viwanda vya nguo", "Soko la Kariakoo", "Bandari kuu"],
    options_en: ["Peninsula and entertainment areas", "Textile factories", "Kariakoo market", "Main port"],
    answer: "Peninsula na maeneo ya burudani",
    answer_en: "Peninsula and entertainment areas",
    explanation: "Msasani Peninsula ni eneo maarufu la burudani na mikahawa Dar es Salaam, likipendwa na wageni na wenyeji.",
    explanation_en: "Msasani Peninsula is a popular entertainment and restaurant area in Dar es Salaam, favoured by both visitors and locals.",
    difficulty: "easy",
  },
  {
    id: "q278",
    category: "Mitaa ya Dar",
    question: "Mtaa wa Mwenge unajulikana kwa soko la nini?",
    question_en: "Mwenge neighbourhood is known for the market selling what?",
    options: ["Sanaa na bidhaa za mbao", "Samaki", "Matunda", "Nguo"],
    options_en: ["Art and woodcraft items", "Fish", "Fruits", "Clothes"],
    answer: "Sanaa na bidhaa za mbao",
    answer_en: "Art and woodcraft items",
    explanation: "Soko la Mwenge linajulikana kwa sanaa za mbao, mafungo, na bidhaa za kitamaduni Tanzania, maarufu kwa watalii.",
    explanation_en: "Mwenge market is known for wooden crafts, carvings, and Tanzanian traditional goods, popular with tourists.",
    difficulty: "easy",
  },
];
