// Mikoa ya Tanzania q143-q152
export const mikoaQuestions = [
  { id: 'q143', category: 'Mikoa ya Tanzania', question: 'Tanzania ina mikoa mingapi rasmi (hadi 2024)?', question_en: 'How many official regions does Tanzania have (as of 2024)?', options: ['31', '25', '20', '28'], options_en: ['31', '25', '20', '28'], answer: '31', answer_en: '31', explanation: 'Tanzania ina mikoa 31 rasmi baada ya mgawanyiko wa mikoa mipya.', explanation_en: 'Tanzania has 31 official regions following recent administrative divisions.', difficulty: 'hard', timeSensitive: true, reviewAfter: '2028-12-31', reviewReason: 'Tanzania may create additional regions through government decrees.', sourceNote: 'Tanzania 2022 census report lists 31 regions.', sourceUrl: 'https://www.nbs.go.tz' },
  { id: 'q144', category: 'Mikoa ya Tanzania', question: 'Mkoa wa Kilimanjaro unajulikana zaidi kwa nini?', question_en: 'What is Kilimanjaro Region best known for?', options: ['Mlima mrefu zaidi Afrika', 'Madini ya dhahabu', 'Uvuvi wa pwani', 'Kilimo cha mpunga'], options_en: ['Highest mountain in Africa', 'Gold mining', 'Coastal fishing', 'Rice farming'], answer: 'Mlima mrefu zaidi Afrika', answer_en: 'Highest mountain in Africa', explanation: 'Kilimanjaro ni mlima mrefu zaidi barani Afrika, ulio kwenye mkoa wa Kilimanjaro.', explanation_en: 'Kilimanjaro is the highest mountain in Africa, located in Kilimanjaro Region.', difficulty: 'easy' },
  { id: 'q145', category: 'Mikoa ya Tanzania', question: 'Mji Mkuu wa Zanzibar (Stone Town) uko mkoa gani?', question_en: 'Zanzibar City (Stone Town) is in which region?', options: ['Mjini Magharibi', 'Kaskazini Unguja', 'Kusini Unguja', 'Kaskazini Pemba'], options_en: ['Mjini Magharibi', 'North Unguja', 'South Unguja', 'North Pemba'], answer: 'Mjini Magharibi', answer_en: 'Mjini Magharibi', explanation: 'Mji Mkuu wa Zanzibar (Stone Town) upo katika mkoa wa Mjini Magharibi.', explanation_en: 'Zanzibar City (Stone Town) is in Mjini Magharibi region.', difficulty: 'medium' },
  { id: 'q146', category: 'Mikoa ya Tanzania', question: 'Mkoa wa Mwanza uko karibu na ziwa gani kubwa?', question_en: 'Mwanza Region is located near which large lake?', options: ['Ziwa Victoria', 'Ziwa Tanganyika', 'Ziwa Malawi', 'Ziwa Rukwa'], options_en: ['Lake Victoria', 'Lake Tanganyika', 'Lake Malawi', 'Lake Rukwa'], answer: 'Ziwa Victoria', answer_en: 'Lake Victoria', explanation: 'Mwanza ipo kwenye ukanda wa Ziwa Victoria, ziwa kubwa zaidi Afrika.', explanation_en: "Mwanza sits on the shores of Lake Victoria, Africa's largest lake.", difficulty: 'easy' },
  { id: 'q147', category: 'Mikoa ya Tanzania', question: 'Mkoa wa Mbeya unajulikana zaidi kwa kilimo cha nini?', question_en: 'Mbeya Region is especially known for growing what?', options: ['Kahawa na chai', 'Karafuu', 'Pamba', 'Korosho'], options_en: ['Coffee and tea', 'Cloves', 'Cotton', 'Cashew nuts'], answer: 'Kahawa na chai', answer_en: 'Coffee and tea', explanation: 'Mbeya inajulikana kwa kilimo cha kahawa na chai katika nyanda za juu kusini.', explanation_en: 'Mbeya is known for coffee and tea cultivation in the southern highlands.', difficulty: 'medium' },
  { id: 'q148', category: 'Mikoa ya Tanzania', question: 'Mji wa Arusha unajulikana kama "Mji wa" nini?', question_en: 'Arusha city is known as the city of what?', options: ['Amani ya Afrika', 'Kilimo', 'Dhahabu', 'Uvuvi'], options_en: ['African Peace', 'Agriculture', 'Gold', 'Fishing'], answer: 'Amani ya Afrika', answer_en: 'African Peace', explanation: 'Arusha imepata jina "Mji wa Amani ya Afrika" kutokana na mikutano mingi ya kimataifa.', explanation_en: 'Arusha earned the title "City of African Peace" due to many international conferences held there.', difficulty: 'medium' },
  { id: 'q149', category: 'Mikoa ya Tanzania', question: 'Mkoa wa Lindi uko sehemu gani ya Tanzania?', question_en: 'Lindi Region is in which part of Tanzania?', options: ['Kusini mashariki', 'Kaskazini', 'Magharibi', 'Kati'], options_en: ['South-east', 'North', 'West', 'Central'], answer: 'Kusini mashariki', answer_en: 'South-east', explanation: 'Lindi ipo sehemu ya kusini mashariki ya Tanzania, karibu na pwani.', explanation_en: 'Lindi is in south-eastern Tanzania, near the coast.', difficulty: 'medium' },
  { id: 'q150', category: 'Mikoa ya Tanzania', question: 'Mkoa gani una Hifadhi ya Taifa ya Serengeti?', question_en: 'Which region contains Serengeti National Park?', options: ['Mara', 'Arusha', 'Mwanza', 'Shinyanga'], options_en: ['Mara', 'Arusha', 'Mwanza', 'Shinyanga'], answer: 'Mara', answer_en: 'Mara', explanation: 'Hifadhi ya Serengeti ipo ndani ya mkoa wa Mara kaskazini mwa Tanzania.', explanation_en: 'Serengeti National Park falls within Mara Region in northern Tanzania.', difficulty: 'medium' },
  { id: 'q151', category: 'Mikoa ya Tanzania', question: 'Mkoa wa Tanga unajulikana zaidi kwa zao gani la biashara?', question_en: 'Tanga Region is best known for which cash crop?', options: ['Sisal', 'Kahawa', 'Pamba', 'Karafuu'], options_en: ['Sisal', 'Coffee', 'Cotton', 'Cloves'], answer: 'Sisal', answer_en: 'Sisal', explanation: 'Tanga ilikuwa miongoni mwa wazalishaji wakubwa wa sisal duniani.', explanation_en: "Tanga was among the world's largest sisal producers.", difficulty: 'medium' },
  { id: 'q152', category: 'Mikoa ya Tanzania', question: 'Jiji la pili kwa ukubwa Tanzania baada ya Dar es Salaam ni lipi?', question_en: "Which is Tanzania's second largest city after Dar es Salaam?", options: ['Mwanza', 'Arusha', 'Dodoma', 'Mbeya'], options_en: ['Mwanza', 'Arusha', 'Dodoma', 'Mbeya'], answer: 'Mwanza', answer_en: 'Mwanza', explanation: 'Mwanza ni jiji la pili kwa ukubwa Tanzania, likiwa bandari muhimu ya Ziwa Victoria.', explanation_en: "Mwanza is Tanzania's second largest city and a key port on Lake Victoria.", difficulty: 'medium' },
];
