// Mitaa ya Dar batch 3 — q351–q358
export const mitaaC = [
  {
    id: "q351",
    category: "Mitaa ya Dar",
    question: "Mtaa wa Kariakoo uliitwa hivyo kwa sababu gani?",
    question_en: "How did the Kariakoo neighbourhood get its name?",
    options: ["Kutoka 'Carrier Corps' ya Vita vya Kwanza vya Dunia", "Kutoka jina la chifu wa eneo", "Kutoka lugha ya Kiarabu", "Kutoka jina la mto"],
    options_en: ["From 'Carrier Corps' of World War One", "From the name of a local chief", "From an Arabic word", "From the name of a river"],
    answer: "Kutoka 'Carrier Corps' ya Vita vya Kwanza vya Dunia",
    answer_en: "From 'Carrier Corps' of World War One",
    explanation: "Kariakoo lilipata jina lake kutoka 'Carrier Corps', kikosi cha wabeba mizigo cha Waingereza wakati wa Vita vya Kwanza vya Dunia.",
    explanation_en: "Kariakoo got its name from the 'Carrier Corps', the British porter unit during World War One who were based in the area.",
    difficulty: "hard",
  },
  {
    id: "q352",
    category: "Mitaa ya Dar",
    question: "Kisiwa cha Kigamboni kipo upande gani wa Dar es Salaam?",
    question_en: "Kigamboni peninsula is on which side of Dar es Salaam?",
    options: ["Kusini mashariki", "Kaskazini magharibi", "Mashariki ya mbali", "Kaskazini mashariki"],
    options_en: ["South-east", "North-west", "Far east", "North-east"],
    answer: "Kusini mashariki",
    answer_en: "South-east",
    explanation: "Kigamboni (pia inaitwa South Beach) ipo kusini mashariki mwa Dar es Salaam, ikitengwa na bandari na mji mkuu na kufikika kwa kivuko cha maji.",
    explanation_en: "Kigamboni (also known as South Beach) is south-east of Dar es Salaam's city centre, separated by the harbour and reached by water ferry.",
    difficulty: "medium",
  },
  {
    id: "q353",
    category: "Mitaa ya Dar",
    question: "Jengo maarufu la kibiashara 'Golden Jubilee Towers' lipo mtaa gani wa Dar es Salaam?",
    question_en: "The famous commercial building 'Golden Jubilee Towers' is in which Dar es Salaam area?",
    options: ["Kivukoni / City Centre", "Kariakoo", "Ubungo", "Kinondoni"],
    options_en: ["Kivukoni / City Centre", "Kariakoo", "Ubungo", "Kinondoni"],
    answer: "Kivukoni / City Centre",
    answer_en: "Kivukoni / City Centre",
    explanation: "Golden Jubilee Towers ipo katikati ya mji wa Dar es Salaam, eneo la Kivukoni, karibu na bahari na majengo ya serikali.",
    explanation_en: "Golden Jubilee Towers is located in Dar es Salaam's city centre in the Kivukoni area, near the waterfront and government buildings.",
    difficulty: "medium",
  },
  {
    id: "q354",
    category: "Mitaa ya Dar",
    question: "Mtaa wa Ilala ni makao makuu ya wilaya gani?",
    question_en: "Ilala neighbourhood is the headquarters of which district?",
    options: ["Wilaya ya Ilala", "Wilaya ya Kinondoni", "Wilaya ya Temeke", "Wilaya ya Ubungo"],
    options_en: ["Ilala District", "Kinondoni District", "Temeke District", "Ubungo District"],
    answer: "Wilaya ya Ilala",
    answer_en: "Ilala District",
    explanation: "Ilala ndiyo makao makuu ya Wilaya ya Ilala, moja ya wilaya kuu za Dar es Salaam inayojumuisha eneo la katikati ya mji.",
    explanation_en: "Ilala is the headquarters of Ilala District, one of Dar es Salaam's main districts encompassing the city centre area.",
    difficulty: "easy",
  },
  {
    id: "q355",
    category: "Mitaa ya Dar",
    question: "Mtaa wa Tabata unajulikana kwa nini?",
    question_en: "What is the Tabata neighbourhood known for?",
    options: ["Hospitali ya Muhimbili na makazi ya watu wengi", "Soko kubwa la samaki", "Vituo vya utalii", "Viwanda vikubwa"],
    options_en: ["Muhimbili Hospital and dense residential areas", "Large fish market", "Tourist centres", "Major factories"],
    answer: "Hospitali ya Muhimbili na makazi ya watu wengi",
    answer_en: "Muhimbili Hospital and dense residential areas",
    explanation: "Tabata ni mtaa wa makazi ulio karibu na Hospitali ya Taifa ya Muhimbili na unajulikana kwa msongamano mkubwa wa watu.",
    explanation_en: "Tabata is a residential neighbourhood near Muhimbili National Hospital and is known for its dense population.",
    difficulty: "medium",
  },
  {
    id: "q356",
    category: "Mitaa ya Dar",
    question: "Kituo kikuu cha mabasi ya daladala Dar es Salaam kipo wapi?",
    question_en: "Where is the main daladala bus terminal in Dar es Salaam?",
    options: ["Kariakoo / Mnazi Mmoja", "Ubungo", "Temeke", "Mwenge"],
    options_en: ["Kariakoo / Mnazi Mmoja", "Ubungo", "Temeke", "Mwenge"],
    answer: "Kariakoo / Mnazi Mmoja",
    answer_en: "Kariakoo / Mnazi Mmoja",
    explanation: "Eneo la Kariakoo na Mnazi Mmoja ndiyo kituo kikuu cha daladala Dar es Salaam, ambapo njia nyingi za usafiri huanza na kuishia.",
    explanation_en: "The Kariakoo and Mnazi Mmoja area is the main daladala hub in Dar es Salaam, where many transport routes start and terminate.",
    difficulty: "easy",
  },
  {
    id: "q357",
    category: "Mitaa ya Dar",
    question: "Jengo la Bunge la Mapinduzi Zanzibar lipo wapi Dar es Salaam?",
    question_en: "Where is the Union Parliament building located in Dar es Salaam?",
    options: ["Dar es Salaam haina Bunge — Bunge lipo Dodoma", "Kariakoo", "Oyster Bay", "Kinondoni"],
    options_en: ["Dar es Salaam has no Parliament — Parliament is in Dodoma", "Kariakoo", "Oyster Bay", "Kinondoni"],
    answer: "Dar es Salaam haina Bunge — Bunge lipo Dodoma",
    answer_en: "Dar es Salaam has no Parliament — Parliament is in Dodoma",
    explanation: "Bunge la Tanzania lipo Dodoma, mji mkuu rasmi, si Dar es Salaam. Dar es Salaam ni kitovu cha biashara tu.",
    explanation_en: "Tanzania's Parliament is in Dodoma, the official capital, not in Dar es Salaam. Dar es Salaam is the commercial hub only.",
    difficulty: "medium",
  },
  {
    id: "q358",
    category: "Mitaa ya Dar",
    question: "Mtaa wa Chang'ombe unajulikana kwa nini Dar es Salaam?",
    question_en: "What is Chang'ombe neighbourhood known for in Dar es Salaam?",
    options: ["Makao ya Jeshi la Tanzania na Chuo cha Sayansi", "Soko la Samaki", "Makao ya Mabalozi", "Bandari ya Uvuvi"],
    options_en: ["Tanzania Army headquarters and Science College", "Fish market", "Embassy residences", "Fishing harbour"],
    answer: "Makao ya Jeshi la Tanzania na Chuo cha Sayansi",
    answer_en: "Tanzania Army headquarters and Science College",
    explanation: "Chang'ombe, wilayani Temeke, inajulikana kwa makao makuu ya Jeshi la Wananchi Tanzania (JWTZ) na taasisi za elimu ya sayansi.",
    explanation_en: "Chang'ombe, in Temeke District, is known for the Tanzania People's Defence Force (TPDF) headquarters and science education institutions.",
    difficulty: "hard",
  },
];
