// Mitaa ya Dar batch 5 — q487–q490
export const mitaaE = [
  {
    id: "q487",
    category: "Mitaa ya Dar",
    question: "Mtaa wa Tegeta uko upande gani wa Dar es Salaam?",
    question_en: "Tegeta neighbourhood is in which part of Dar es Salaam?",
    options: ["Kaskazini (Kinondoni)", "Kusini (Temeke)", "Mashariki", "Katikati ya mji"],
    options_en: ["North (Kinondoni)", "South (Temeke)", "East", "City Centre"],
    answer: "Kaskazini (Kinondoni)",
    answer_en: "North (Kinondoni)",
    explanation: "Tegeta ni mtaa wa kaskazini ya Dar es Salaam, uliopo wilaya ya Kinondoni, na umekua haraka kwa miaka ya hivi karibuni.",
    explanation_en: "Tegeta is a northern Dar es Salaam neighbourhood in Kinondoni District that has grown rapidly in recent years.",
    difficulty: "medium",
  },
  {
    id: "q488",
    category: "Mitaa ya Dar",
    question: "Mtaa gani wa Dar es Salaam unajulikana kwa soko kubwa la samaki?",
    question_en: "Which Dar es Salaam neighbourhood is known for a large fish market?",
    options: ["Feri / Kunduchi", "Kariakoo", "Ubungo", "Mwenge"],
    options_en: ["Feri / Kunduchi", "Kariakoo", "Ubungo", "Mwenge"],
    answer: "Feri / Kunduchi",
    answer_en: "Feri / Kunduchi",
    explanation: "Maeneo ya pwani kaskazini ya Dar es Salaam kama Kunduchi na Feri yana masoko ya samaki yanayopatikana hasa asubuhi na mapema.",
    explanation_en: "Coastal areas in northern Dar es Salaam such as Kunduchi and Feri have busy fish markets active especially in the early morning.",
    difficulty: "medium",
  },
  {
    id: "q489",
    category: "Mitaa ya Dar",
    question: "Kituo cha BRT (Bus Rapid Transit) cha Dar es Salaam kimepewa jina gani rasmi?",
    question_en: "Dar es Salaam's BRT (Bus Rapid Transit) system has what official name?",
    options: ["DART (Dar es Salaam Rapid Transit)", "Dar BRT", "Mwendo Wa Haraka", "Daladala ya Express"],
    options_en: ["DART (Dar es Salaam Rapid Transit)", "Dar BRT", "Mwendo Wa Haraka", "Daladala ya Express"],
    answer: "DART (Dar es Salaam Rapid Transit)",
    answer_en: "DART (Dar es Salaam Rapid Transit)",
    explanation: "Mfumo wa mabasi ya haraka wa Dar es Salaam unaitwa DART (Dar es Salaam Rapid Transit), ukiwa mojawapo ya miradi mikubwa ya usafiri wa umma Tanzania.",
    explanation_en: "Dar es Salaam's bus rapid transit system is called DART (Dar es Salaam Rapid Transit), one of Tanzania's major public transport projects.",
    difficulty: "medium",
  },
  {
    id: "q490",
    category: "Mitaa ya Dar",
    question: "Mtaa wa Masaki uko eneo gani la Dar es Salaam?",
    question_en: "Masaki neighbourhood is in which part of Dar es Salaam?",
    options: ["Peninsula ya kaskazini mashariki (Msasani Peninsula)", "Katikati ya mji", "Kusini ya mji", "Karibu na uwanja wa ndege"],
    options_en: ["North-eastern peninsula (Msasani Peninsula)", "City centre", "South of the city", "Near the airport"],
    answer: "Peninsula ya kaskazini mashariki (Msasani Peninsula)",
    answer_en: "North-eastern peninsula (Msasani Peninsula)",
    explanation: "Masaki ni mtaa wa hali ya juu kwenye Msasani Peninsula, kaskazini mashariki ya Dar es Salaam, ukijulikana kwa makazi mazuri na mikahawa ya bahari.",
    explanation_en: "Masaki is an upmarket neighbourhood on Msasani Peninsula in north-eastern Dar es Salaam, known for fine residences and waterfront restaurants.",
    difficulty: "easy",
  },
];
