// Mikoa ya Tanzania batch 3 — q319–q326
export const mikoaC = [
  {
    id: "q319",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Lindi unapakana na nchi gani kusini?",
    question_en: "Lindi Region borders which country to the south?",
    options: ["Msumbiji (Mozambique)", "Malawi", "Zambia", "Zimbabwe"],
    options_en: ["Mozambique", "Malawi", "Zambia", "Zimbabwe"],
    answer: "Msumbiji (Mozambique)",
    answer_en: "Mozambique",
    explanation: "Mkoa wa Lindi unapakana na Msumbiji (Mozambique) kusini, kupitia Mto Ruvuma.",
    explanation_en: "Lindi Region borders Mozambique to the south, separated by the Ruvuma River.",
    difficulty: "medium",
  },
  {
    id: "q320",
    category: "Mikoa ya Tanzania",
    question: "Mji gani ndiyo mji mkubwa zaidi wa mkoa wa Mwanza?",
    question_en: "Which city is the largest in Mwanza Region?",
    options: ["Mwanza", "Musoma", "Bukoba", "Shinyanga"],
    options_en: ["Mwanza", "Musoma", "Bukoba", "Shinyanga"],
    answer: "Mwanza",
    answer_en: "Mwanza",
    explanation: "Mwanza ndiyo mji mkubwa zaidi wa mkoa wa Mwanza na mji wa pili kwa ukubwa Tanzania, ukiwa pwani ya Ziwa Victoria.",
    explanation_en: "Mwanza is the largest city in Mwanza Region and Tanzania's second largest city, situated on the shores of Lake Victoria.",
    difficulty: "easy",
  },
  {
    id: "q321",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Iringa unajulikana kwa zao gani la kilimo?",
    question_en: "Iringa Region is known for which agricultural product?",
    options: ["Chai (Tea)", "Kahawa (Coffee)", "Pamba (Cotton)", "Miwa (Sugarcane)"],
    options_en: ["Tea", "Coffee", "Cotton", "Sugarcane"],
    answer: "Chai (Tea)",
    answer_en: "Tea",
    explanation: "Mkoa wa Iringa, hasa eneo la Mufindi, unajulikana kwa uzalishaji mkubwa wa chai ya ubora wa juu Tanzania.",
    explanation_en: "Iringa Region, particularly the Mufindi area, is known for producing high-quality tea in Tanzania.",
    difficulty: "medium",
  },
  {
    id: "q322",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Tabora unajulikana kwa zao gani la kibiashara?",
    question_en: "Tabora Region is known for which cash crop?",
    options: ["Tumbaku (Tobacco)", "Kahawa", "Chai", "Pamba"],
    options_en: ["Tobacco", "Coffee", "Tea", "Cotton"],
    answer: "Tumbaku (Tobacco)",
    answer_en: "Tobacco",
    explanation: "Mkoa wa Tabora ni mzalishaji mkubwa wa tumbaku Tanzania, kilimo ambacho kimekuwa chanzo cha mapato kwa muda mrefu.",
    explanation_en: "Tabora Region is a major tobacco producer in Tanzania, a crop that has long been a significant source of income.",
    difficulty: "medium",
  },
  {
    id: "q323",
    category: "Mikoa ya Tanzania",
    question: "Mikoa mingapi ya Tanzania Bara ipo nchini?",
    question_en: "How many regions does mainland Tanzania (Tanzania Bara) have?",
    options: ["26", "25", "30", "21"],
    options_en: ["26", "25", "30", "21"],
    answer: "26",
    answer_en: "26",
    explanation: "Tanzania Bara (mainland) ina mikoa 26, na Zanzibar ina mikoa 5, ikifanya jumla ya mikoa 31 nchini Tanzania.",
    explanation_en: "Mainland Tanzania has 26 regions, while Zanzibar has 5 regions, making a total of 31 regions in Tanzania.",
    difficulty: "hard",
    timeSensitive: true,
    reviewAfter: "2028-12-31",
    reviewReason: "Regional count may change if new regions are created on the mainland.",
    sourceNote: "Tanzania mainland had 26 regions as of 2024 administrative structure.",
    sourceUrl: "https://www.parliament.go.tz",
  },
  {
    id: "q324",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Arusha unajulikana kwa kitu gani muhimu nje ya hifadhi za wanyama?",
    question_en: "Arusha Region is notable for what important thing besides wildlife parks?",
    options: ["Makao makuu ya Mahakama ya Kimataifa (ICTR)", "Makao makuu ya Umoja wa Afrika", "Bunge la Afrika Mashariki", "Benki ya Dunia tawi la Afrika"],
    options_en: ["Headquarters of the International Criminal Tribunal (ICTR)", "African Union headquarters", "East African Legislative Assembly", "World Bank Africa branch"],
    answer: "Makao makuu ya Mahakama ya Kimataifa (ICTR)",
    answer_en: "Headquarters of the International Criminal Tribunal (ICTR)",
    explanation: "Arusha ilikuwa makao makuu ya ICTR (Mahakama ya Kimataifa ya Rwanda) na sasa ni nyumbani kwa Mahakama ya Kimataifa ya Jinai ya Afrika.",
    explanation_en: "Arusha was home to the ICTR (International Criminal Tribunal for Rwanda) and now hosts the International Residual Mechanism for Criminal Tribunals.",
    difficulty: "hard",
  },
  {
    id: "q325",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Pemba Kaskazini na Pemba Kusini vipo ndani ya utawala wa nani?",
    question_en: "The North Pemba and South Pemba regions fall under whose administration?",
    options: ["Serikali ya Mapinduzi Zanzibar", "Serikali ya Tanzania Bara", "Serikali ya Pamoja", "Serikali ya Shirikisho"],
    options_en: ["Zanzibar Revolutionary Government", "Tanzania Mainland Government", "Joint Government", "Federal Government"],
    answer: "Serikali ya Mapinduzi Zanzibar",
    answer_en: "Zanzibar Revolutionary Government",
    explanation: "Mikoa ya Pemba Kaskazini na Pemba Kusini ipo chini ya Serikali ya Mapinduzi Zanzibar (SMZ), si serikali ya Tanzania Bara.",
    explanation_en: "North and South Pemba regions fall under the Zanzibar Revolutionary Government (ZRG), not the Tanzania mainland government.",
    difficulty: "medium",
  },
  {
    id: "q326",
    category: "Mikoa ya Tanzania",
    question: "Mkoa gani wa Tanzania una ziwa la chumvi linaloitwa Eyasi?",
    question_en: "Which Tanzanian region contains the salt lake called Eyasi?",
    options: ["Arusha", "Manyara", "Kilimanjaro", "Dodoma"],
    options_en: ["Arusha", "Manyara", "Kilimanjaro", "Dodoma"],
    answer: "Manyara",
    answer_en: "Manyara",
    explanation: "Ziwa Eyasi ni ziwa la chumvi lililopo mkoa wa Manyara, kusini mwa Crater ya Ngorongoro, likiwa nyumbani kwa kabila la Hadza.",
    explanation_en: "Lake Eyasi is a salt lake in Manyara Region, south of the Ngorongoro Crater, and is home to the Hadza people.",
    difficulty: "hard",
  },
];
