// Mikoa ya Tanzania batch 2 — q239–q246
export const mikoaB = [
  {
    id: "q239",
    category: "Mikoa ya Tanzania",
    question: "Mkoa gani wa Tanzania una Mlima Kilimanjaro?",
    question_en: "Which region of Tanzania contains Mount Kilimanjaro?",
    options: ["Kilimanjaro", "Arusha", "Moshi", "Tanga"],
    options_en: ["Kilimanjaro", "Arusha", "Moshi", "Tanga"],
    answer: "Kilimanjaro",
    answer_en: "Kilimanjaro",
    explanation: "Mlima Kilimanjaro upo mkoa wa Kilimanjaro, kaskazini mwa Tanzania, karibu na mji wa Moshi.",
    explanation_en: "Mount Kilimanjaro is in Kilimanjaro Region, northern Tanzania, near the town of Moshi.",
    difficulty: "easy",
  },
  {
    id: "q240",
    category: "Mikoa ya Tanzania",
    question: "Ziwa Tanganyika linapakana na mikoa gani ya Tanzania upande wa magharibi?",
    question_en: "Lake Tanganyika borders which Tanzanian regions on the western side?",
    options: ["Kigoma na Katavi", "Rukwa na Ruvuma", "Tabora na Mbeya", "Kagera na Mara"],
    options_en: ["Kigoma and Katavi", "Rukwa and Ruvuma", "Tabora and Mbeya", "Kagera and Mara"],
    answer: "Kigoma na Katavi",
    answer_en: "Kigoma and Katavi",
    explanation: "Ziwa Tanganyika linapakana na mikoa ya Kigoma na Katavi upande wa magharibi wa Tanzania.",
    explanation_en: "Lake Tanganyika borders the Kigoma and Katavi regions on the western side of Tanzania.",
    difficulty: "hard",
  },
  {
    id: "q241",
    category: "Mikoa ya Tanzania",
    question: "Mkoa gani wa Tanzania una bandari ya Mtwara?",
    question_en: "Which Tanzanian region has Mtwara port?",
    options: ["Mtwara", "Lindi", "Pwani", "Tanga"],
    options_en: ["Mtwara", "Lindi", "Pwani", "Tanga"],
    answer: "Mtwara",
    answer_en: "Mtwara",
    explanation: "Bandari ya Mtwara ipo mkoa wa Mtwara, kusini mwa Tanzania, na ni bandari muhimu ya biashara.",
    explanation_en: "Mtwara port is in Mtwara Region, southern Tanzania, and is an important trade port.",
    difficulty: "easy",
  },
  {
    id: "q242",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Dodoma ni muhimu kwa sababu gani?",
    question_en: "Dodoma Region is significant for what reason?",
    options: ["Ni mji mkuu wa Tanzania", "Una madini ya dhahabu", "Ni bandari kubwa", "Una hifadhi ya Serengeti"],
    options_en: ["It is the capital of Tanzania", "It has gold mines", "It is a major port", "It has Serengeti Park"],
    answer: "Ni mji mkuu wa Tanzania",
    answer_en: "It is the capital of Tanzania",
    explanation: "Dodoma ni mji mkuu rasmi wa Tanzania tangu 1996, ingawa Dar es Salaam bado ni kitovu cha biashara.",
    explanation_en: "Dodoma has been the official capital of Tanzania since 1996, although Dar es Salaam remains the commercial hub.",
    difficulty: "easy",
  },
  {
    id: "q243",
    category: "Mikoa ya Tanzania",
    question: "Kisiwa cha Zanzibar kipo mkoa gani?",
    question_en: "Zanzibar Island falls under which region?",
    options: ["Unguja Kaskazini na Kusini", "Pwani", "Dar es Salaam", "Tanga"],
    options_en: ["North and South Unguja", "Pwani", "Dar es Salaam", "Tanga"],
    answer: "Unguja Kaskazini na Kusini",
    answer_en: "North and South Unguja",
    explanation: "Zanzibar (Unguja) imegawanywa katika mikoa miwili: Unguja Kaskazini na Unguja Kusini, ndani ya Serikali ya Mapinduzi Zanzibar.",
    explanation_en: "Zanzibar (Unguja) is divided into two regions: North Unguja and South Unguja, within the Zanzibar Revolutionary Government.",
    difficulty: "medium",
  },
  {
    id: "q244",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Kagera unapakana na nchi gani upande wa kaskazini?",
    question_en: "Kagera Region borders which country to the north?",
    options: ["Uganda", "Kenya", "Rwanda", "Burundi"],
    options_en: ["Uganda", "Kenya", "Rwanda", "Burundi"],
    answer: "Uganda",
    answer_en: "Uganda",
    explanation: "Mkoa wa Kagera unapakana na Uganda kaskazini, Rwanda na Burundi magharibi, na Ziwa Victoria mashariki.",
    explanation_en: "Kagera Region borders Uganda to the north, Rwanda and Burundi to the west, and Lake Victoria to the east.",
    difficulty: "medium",
  },
  {
    id: "q245",
    category: "Mikoa ya Tanzania",
    question: "Mkoa gani wa Tanzania unajulikana kwa uzalishaji mkubwa wa kahawa?",
    question_en: "Which Tanzanian region is well known for large-scale coffee production?",
    options: ["Kilimanjaro", "Arusha", "Mbeya", "Iringa"],
    options_en: ["Kilimanjaro", "Arusha", "Mbeya", "Iringa"],
    answer: "Kilimanjaro",
    answer_en: "Kilimanjaro",
    explanation: "Mkoa wa Kilimanjaro unajulikana kwa uzalishaji wa kahawa ya Arabica ya ubora wa juu, inayosifika duniani.",
    explanation_en: "Kilimanjaro Region is renowned for producing high-quality Arabica coffee that is celebrated worldwide.",
    difficulty: "medium",
  },
  {
    id: "q246",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Mwanza unapakana na ziwa gani kubwa?",
    question_en: "Mwanza Region borders which large lake?",
    options: ["Ziwa Victoria", "Ziwa Tanganyika", "Ziwa Nyasa", "Ziwa Rukwa"],
    options_en: ["Lake Victoria", "Lake Tanganyika", "Lake Nyasa", "Lake Rukwa"],
    answer: "Ziwa Victoria",
    answer_en: "Lake Victoria",
    explanation: "Mwanza ni mji mkubwa kwenye ukingo wa Ziwa Victoria, ziwa kubwa zaidi Afrika.",
    explanation_en: "Mwanza is a major city on the shores of Lake Victoria, the largest lake in Africa.",
    difficulty: "easy",
  },
];
