// Mikoa ya Tanzania batch 4 — q399–q406
export const mikoaD = [
  {
    id: "q399",
    category: "Mikoa ya Tanzania",
    question: "Mkoa gani wa Tanzania unajulikana kwa uzalishaji wa sukari?",
    question_en: "Which Tanzanian region is known for sugar production?",
    options: ["Morogoro (Kilombero)", "Mwanza", "Iringa", "Dodoma"],
    options_en: ["Morogoro (Kilombero)", "Mwanza", "Iringa", "Dodoma"],
    answer: "Morogoro (Kilombero)",
    answer_en: "Morogoro (Kilombero)",
    explanation: "Bonde la Kilombero mkoa wa Morogoro ni eneo kubwa la uzalishaji wa sukari Tanzania, nyumbani kwa kiwanda kikubwa cha sukari.",
    explanation_en: "The Kilombero Valley in Morogoro Region is Tanzania's main sugar-producing area, home to a large sugar processing plant.",
    difficulty: "medium",
  },
  {
    id: "q400",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Songwe ulianzishwa mwaka gani kama mkoa mpya?",
    question_en: "Songwe Region was established as a new region in which year?",
    options: ["2016", "2010", "2012", "2020"],
    options_en: ["2016", "2010", "2012", "2020"],
    answer: "2016",
    answer_en: "2016",
    explanation: "Mkoa wa Songwe ulianzishwa mwaka 2016 ukitenganishwa na mkoa wa Mbeya, ukiwa mkoa wa 31 Tanzania.",
    explanation_en: "Songwe Region was established in 2016, carved out of Mbeya Region, making it Tanzania's 31st region.",
    difficulty: "hard",
    sourceNote: "Songwe Region was created in 2016 by presidential decree.",
    sourceUrl: "https://www.parliament.go.tz",
  },
  {
    id: "q401",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Katavi unajulikana kwa nini?",
    question_en: "What is Katavi Region known for?",
    options: ["Hifadhi ya Taifa ya Katavi na wanyama wengi", "Uzalishaji wa kahawa", "Madini ya dhahabu", "Bandari ya samaki"],
    options_en: ["Katavi National Park and abundant wildlife", "Coffee production", "Gold mining", "Fish harbour"],
    answer: "Hifadhi ya Taifa ya Katavi na wanyama wengi",
    answer_en: "Katavi National Park and abundant wildlife",
    explanation: "Mkoa wa Katavi unajulikana kwa Hifadhi ya Taifa ya Katavi, ambayo ina idadi kubwa ya nyati, kiboko, na tembo.",
    explanation_en: "Katavi Region is known for Katavi National Park, which has large populations of buffalo, hippo, and elephant.",
    difficulty: "medium",
  },
  {
    id: "q402",
    category: "Mikoa ya Tanzania",
    question: "Mji mkuu wa mkoa wa Manyara ni upi?",
    question_en: "What is the regional capital of Manyara Region?",
    options: ["Babati", "Arusha", "Karatu", "Monduli"],
    options_en: ["Babati", "Arusha", "Karatu", "Monduli"],
    answer: "Babati",
    answer_en: "Babati",
    explanation: "Babati ndiyo mji mkuu wa mkoa wa Manyara, mkoa ulioundwa baada ya kugawanywa na mkoa wa Arusha mwaka 2002.",
    explanation_en: "Babati is the regional capital of Manyara Region, which was formed after being split from Arusha Region in 2002.",
    difficulty: "hard",
  },
  {
    id: "q403",
    category: "Mikoa ya Tanzania",
    question: "Mkoa gani wa Tanzania unapakana na Malawi na Zambia?",
    question_en: "Which Tanzanian region borders both Malawi and Zambia?",
    options: ["Rukwa", "Mbeya", "Songwe", "Ruvuma"],
    options_en: ["Rukwa", "Mbeya", "Songwe", "Ruvuma"],
    answer: "Rukwa",
    answer_en: "Rukwa",
    explanation: "Mkoa wa Rukwa unapakana na Zambia magharibi na una mpaka wa karibu na Malawi kupitia Ziwa Nyasa (Malawi).",
    explanation_en: "Rukwa Region borders Zambia to the west and has proximity to Malawi through Lake Nyasa.",
    difficulty: "hard",
  },
  {
    id: "q404",
    category: "Mikoa ya Tanzania",
    question: "Ziwa Nyasa (Lake Malawi) linagawanwa na nchi zipi?",
    question_en: "Lake Nyasa (Lake Malawi) is shared by which countries?",
    options: ["Tanzania, Malawi, Msumbiji", "Tanzania, Kenya, Uganda", "Tanzania, Zambia, DRC", "Tanzania, Rwanda, Burundi"],
    options_en: ["Tanzania, Malawi, Mozambique", "Tanzania, Kenya, Uganda", "Tanzania, Zambia, DRC", "Tanzania, Rwanda, Burundi"],
    answer: "Tanzania, Malawi, Msumbiji",
    answer_en: "Tanzania, Malawi, Mozambique",
    explanation: "Ziwa Nyasa (Lake Malawi) linagawanwa na Tanzania kaskazini, Malawi magharibi, na Msumbiji kusini mashariki.",
    explanation_en: "Lake Nyasa is shared by Tanzania to the north, Malawi to the west, and Mozambique to the south-east.",
    difficulty: "medium",
  },
  {
    id: "q405",
    category: "Mikoa ya Tanzania",
    question: "Mkoa gani wa Tanzania una jangwa la Chalbi na mandhari kame?",
    question_en: "Which Tanzanian region has semi-arid landscape around the central plateau?",
    options: ["Dodoma", "Arusha", "Mwanza", "Iringa"],
    options_en: ["Dodoma", "Arusha", "Mwanza", "Iringa"],
    answer: "Dodoma",
    answer_en: "Dodoma",
    explanation: "Mkoa wa Dodoma una hali ya hewa kame na nusu kame, ukiwa mji mkuu wa Tanzania katikati ya nchi kwenye nyanda za juu.",
    explanation_en: "Dodoma Region has arid and semi-arid conditions, situated in the country's central plateau — Tanzania's official capital.",
    difficulty: "easy",
  },
  {
    id: "q406",
    category: "Mikoa ya Tanzania",
    question: "Mkoa wa Shinyanga unajulikana kwa uzalishaji wa nini?",
    question_en: "Shinyanga Region is known for producing what?",
    options: ["Almasi (Diamonds)", "Dhahabu (Gold)", "Kahawa (Coffee)", "Chai (Tea)"],
    options_en: ["Diamonds", "Gold", "Coffee", "Tea"],
    answer: "Almasi (Diamonds)",
    answer_en: "Diamonds",
    explanation: "Mkoa wa Shinyanga unajulikana kwa mgodi wa almasi wa Mwadui (Williamson Diamond Mine), mmoja wa migodi mikubwa zaidi ya almasi duniani.",
    explanation_en: "Shinyanga Region is known for the Mwadui (Williamson Diamond Mine), one of the largest diamond mines in the world.",
    difficulty: "medium",
    sourceNote: "The Williamson Diamond Mine at Mwadui, Shinyanga, is Tanzania's main diamond mine.",
    sourceUrl: "https://www.petra-diamonds.com",
  },
];
