// Vyakula vya Bongo q163-q172
export const vyakulaQuestions = [
  { id: 'q163', category: 'Vyakula vya Bongo', question: 'Ugali hutengenezwa kwa unga wa nini?', question_en: 'Ugali is made from flour of what?', options: ['Mahindi', 'Ngano', 'Mchele', 'Mtama'], options_en: ['Maize', 'Wheat', 'Rice', 'Sorghum'], answer: 'Mahindi', answer_en: 'Maize', explanation: 'Ugali wa kawaida Tanzania hutengenezwa kwa unga wa mahindi uliopikwa na maji.', explanation_en: 'The common Tanzanian ugali is made from maize flour cooked with water.', difficulty: 'easy' },
  { id: 'q164', category: 'Vyakula vya Bongo', question: 'Pilau ina mizizi ya utamaduni gani?', question_en: 'Pilau has culinary roots from which culture?', options: ['Kiarabu na Kiajemi', 'Kichina', 'Kihindi peke yake', 'Kiingereza'], options_en: ['Arab and Persian', 'Chinese', 'Indian only', 'British'], answer: 'Kiarabu na Kiajemi', answer_en: 'Arab and Persian', explanation: 'Pilau ina mizizi ya Kiarabu na Kiajemi, ikipikwa zaidi pwani na Zanzibar.', explanation_en: 'Pilau has Arab and Persian roots, cooked mostly on the coast and in Zanzibar.', difficulty: 'medium' },
  { id: 'q165', category: 'Vyakula vya Bongo', question: 'Chakula cha "Wali wa Nazi" kinatumia kiungo gani muhimu?', question_en: 'The dish "Wali wa Nazi" uses which key ingredient?', options: ['Maziwa ya nazi', 'Siagi', 'Mafuta ya alizeti', 'Cream ya maziwa'], options_en: ['Coconut milk', 'Butter', 'Sunflower oil', 'Dairy cream'], answer: 'Maziwa ya nazi', answer_en: 'Coconut milk', explanation: 'Wali wa Nazi ni wali uliopikwa kwa kutumia maziwa ya nazi badala ya maji.', explanation_en: 'Wali wa Nazi is rice cooked using coconut milk instead of water.', difficulty: 'easy' },
  { id: 'q166', category: 'Vyakula vya Bongo', question: 'Kinywaji cha asili cha Wachagga kinachotengenezwa kwa ndizi inaitwa nini?', question_en: 'A traditional Chagga drink made from bananas is called what?', options: ['Mbege', 'Togwa', 'Mnazi', 'Ulanzi'], options_en: ['Mbege', 'Togwa', 'Mnazi', 'Ulanzi'], answer: 'Mbege', answer_en: 'Mbege', explanation: 'Mbege ni kinywaji cha jadi cha Wachagga kilichotengenezwa kwa ndizi na mtama.', explanation_en: 'Mbege is a traditional Chagga drink made from bananas and millet.', difficulty: 'hard' },
  { id: 'q167', category: 'Vyakula vya Bongo', question: 'Mshikaki ni nini hasa?', question_en: 'What exactly is Mshikaki?', options: ['Nyama iliyochomwa kwa fimbo', 'Supu ya mbogamboga', 'Wali na maharage', 'Mkate wa kukaanga'], options_en: ['Meat grilled on skewers', 'Vegetable soup', 'Rice and beans', 'Fried bread'], answer: 'Nyama iliyochomwa kwa fimbo', answer_en: 'Meat grilled on skewers', explanation: 'Mshikaki ni vipande vya nyama vilivyotiwa kwenye fimbo na kuchomwa juu ya mkaa.', explanation_en: 'Mshikaki is pieces of meat placed on skewers and grilled over charcoal.', difficulty: 'easy' },
  { id: 'q168', category: 'Vyakula vya Bongo', question: 'Ndizi za kupika ambazo huliwa zikiwa hazijaivia huitwa nini Tanzania?', question_en: 'Unripe cooking bananas in Tanzania are commonly called what?', options: ['Matoke', 'Ndizi mbivu', 'Ndizi sukari', 'Migomba'], options_en: ['Matoke', 'Ripe bananas', 'Sugar bananas', 'Banana plants'], answer: 'Matoke', answer_en: 'Matoke', explanation: 'Matoke ni ndizi za kupika ambazo huliwa zikiwa hazijaivia, maarufu mikoa ya kaskazini.', explanation_en: 'Matoke are cooking bananas eaten unripe, very popular in northern regions.', difficulty: 'easy' },
  { id: 'q169', category: 'Vyakula vya Bongo', question: 'Maharagwe ya Nazi ni mchanganyiko wa nini?', question_en: 'Maharagwe ya Nazi is a combination of what?', options: ['Maharage na maziwa ya nazi', 'Maharage na nyanya', 'Maharage na nyama', 'Maharage na pilipili kali'], options_en: ['Beans and coconut milk', 'Beans and tomatoes', 'Beans and meat', 'Beans and hot chilli'], answer: 'Maharage na maziwa ya nazi', answer_en: 'Beans and coconut milk', explanation: 'Maharagwe ya Nazi ni sahani ya maharage yaliyopikwa na maziwa ya nazi na viungo.', explanation_en: 'Maharagwe ya Nazi is a dish of beans cooked with coconut milk and spices.', difficulty: 'easy' },
  { id: 'q170', category: 'Vyakula vya Bongo', question: '"Ndizi na Nyama" kinajulikana zaidi mkoa gani?', question_en: '"Ndizi na Nyama" is best known in which region?', options: ['Kagera', 'Dar es Salaam', 'Pwani', 'Dodoma'], options_en: ['Kagera', 'Dar es Salaam', 'Coast', 'Dodoma'], answer: 'Kagera', answer_en: 'Kagera', explanation: 'Ndizi na Nyama ni sahani ya kawaida mkoa wa Kagera kaskazini magharibi mwa Tanzania.', explanation_en: 'Ndizi na Nyama is a staple dish in Kagera Region in north-western Tanzania.', difficulty: 'medium' },
  { id: 'q171', category: 'Vyakula vya Bongo', question: 'Samaki wa kupaka ni sahani inayotumia kiungo gani kikuu cha pwani?', question_en: 'Samaki wa kupaka is a dish using which key coastal ingredient?', options: ['Nazi (nzima au maziwa yake)', 'Tangawizi peke yake', 'Siagi ya maziwa', 'Mafuta ya mizeituni'], options_en: ['Coconut (whole or its milk)', 'Ginger only', 'Butter', 'Olive oil'], answer: 'Nazi (nzima au maziwa yake)', answer_en: 'Coconut (whole or its milk)', explanation: 'Samaki wa kupaka hupakwa na nazi iliyokorogwa na viungo, kisha kuchomwa.', explanation_en: 'Samaki wa kupaka is coated with coconut paste and spices, then grilled.', difficulty: 'medium' },
  { id: 'q172', category: 'Vyakula vya Bongo', question: 'Uji wa mtama hutumika kwa lengo gani la kiafya?', question_en: 'What health purpose does millet porridge (uji wa mtama) serve?', options: ['Kuimarisha mwili na kutoa nishati', 'Kupunguza mafuta tu', 'Kuzuia malaria', 'Kupoza moto wa mwili'], options_en: ['Strengthening the body and providing energy', 'Reducing fat only', 'Preventing malaria', 'Cooling body heat'], answer: 'Kuimarisha mwili na kutoa nishati', answer_en: 'Strengthening the body and providing energy', explanation: 'Uji wa mtama ni chanzo kizuri cha wanga, madini ya chuma, na nishati kwa mwili.', explanation_en: 'Millet porridge is a good source of carbohydrates, iron, and energy for the body.', difficulty: 'medium' },
];
