// Wanyama na Hifadhi q193-q202
export const wanyamaQuestions = [
  { id: 'q193', category: 'Wanyama na Hifadhi', question: 'Ngorongoro ni nini kibaolojia?', question_en: 'What is Ngorongoro biologically?', options: ['Caldera ya volkeno yenye mfumo wa ikolojia unaojitegemea', 'Msitu mkubwa Afrika', 'Ziwa la pekee', 'Hifadhi ya ndege tu'], options_en: ['Volcanic caldera with self-contained ecosystem', 'Largest forest in Africa', 'A unique lake', 'Bird-only sanctuary'], answer: 'Caldera ya volkeno yenye mfumo wa ikolojia unaojitegemea', answer_en: 'Volcanic caldera with self-contained ecosystem', explanation: 'Ngorongoro ni caldera ya volkeno yenye mfumo wa ikolojia unaojitegemea ndani yake.', explanation_en: 'Ngorongoro is a volcanic caldera with a largely self-contained ecosystem inside it.', difficulty: 'medium' },
  { id: 'q194', category: 'Wanyama na Hifadhi', question: 'Tembo wa Afrika huitwa kwa Kiswahili gani?', question_en: 'What is the Swahili name for the African elephant?', options: ['Ndovu', 'Simba', 'Twiga', 'Kiboko'], options_en: ['Ndovu', 'Simba', 'Twiga', 'Kiboko'], answer: 'Ndovu', answer_en: 'Ndovu', explanation: 'Tembo au Ndovu ni jina la Kiswahili la mnyama mkubwa zaidi ardhini.', explanation_en: "Tembo or Ndovu is the Swahili name for the world's largest land animal.", difficulty: 'easy' },
  { id: 'q195', category: 'Wanyama na Hifadhi', question: 'Hifadhi ya Tarangire inajulikana zaidi kwa wanyama gani?', question_en: 'Tarangire National Park is best known for which animals?', options: ['Tembo kwa makundi makubwa', 'Simba wengi', 'Papa wa mto', 'Ndege wa pwani'], options_en: ['Large elephant herds', 'Many lions', 'River sharks', 'Coastal birds'], answer: 'Tembo kwa makundi makubwa', answer_en: 'Large elephant herds', explanation: 'Tarangire inajulikana kwa makundi makubwa ya tembo, hasa wakati wa kiangazi.', explanation_en: 'Tarangire is famous for large elephant herds, especially during the dry season.', difficulty: 'easy' },
  { id: 'q196', category: 'Wanyama na Hifadhi', question: 'Selous Game Reserve sasa inaitwa jina gani jipya?', question_en: 'Selous Game Reserve is now known by what new name?', options: ['Nyerere National Park', 'Ruaha Extension', 'Mikumi Reserve', 'Kilwa Park'], options_en: ['Nyerere National Park', 'Ruaha Extension', 'Mikumi Reserve', 'Kilwa Park'], answer: 'Nyerere National Park', answer_en: 'Nyerere National Park', explanation: 'Selous Game Reserve iliitwa upya Nyerere National Park mwaka 2019.', explanation_en: 'Selous Game Reserve was renamed Nyerere National Park in 2019.', difficulty: 'medium', sourceNote: 'Tanzania government gazette renamed Selous to Nyerere National Park in 2019.' },
  { id: 'q197', category: 'Wanyama na Hifadhi', question: 'Hifadhi ya Ruaha ni ya ukubwa gani Tanzania?', question_en: 'How does Ruaha National Park rank in size in Tanzania?', options: ['Ni kubwa zaidi Tanzania', 'Ni ndogo zaidi', 'Ni ya pili kwa ukubwa', 'Ni ya tatu kwa ukubwa'], options_en: ['It is the largest in Tanzania', 'It is the smallest', 'It is second largest', 'It is third largest'], answer: 'Ni kubwa zaidi Tanzania', answer_en: 'It is the largest in Tanzania', explanation: 'Ruaha National Park ndiyo hifadhi ya taifa kubwa zaidi Tanzania.', explanation_en: 'Ruaha National Park is the largest national park in Tanzania.', difficulty: 'hard' },
  { id: 'q198', category: 'Wanyama na Hifadhi', question: 'Chui ana madoa ya aina gani tofauti na duma?', question_en: 'What type of markings distinguish a leopard from a cheetah?', options: ['Madoa ya mviringo (rosette)', 'Mistari nyeusi laini', 'Madoa mekundu', 'Mistari ya pembe tatu'], options_en: ['Rosette spots', 'Smooth black lines', 'Red spots', 'Triangular stripes'], answer: 'Madoa ya mviringo (rosette)', answer_en: 'Rosette spots', explanation: 'Chui ana madoa ya mviringo (rosette), wakati duma ana mistari nyeusi kutoka machoni.', explanation_en: 'The leopard has rosette markings while the cheetah has solid black tear-line streaks.', difficulty: 'medium' },
  { id: 'q199', category: 'Wanyama na Hifadhi', question: 'Twiga inaweza kufikia urefu gani?', question_en: 'How tall can a giraffe reach?', options: ['Hadi mita 6', 'Hadi mita 3', 'Hadi mita 8', 'Hadi mita 4'], options_en: ['Up to 6 metres', 'Up to 3 metres', 'Up to 8 metres', 'Up to 4 metres'], answer: 'Hadi mita 6', answer_en: 'Up to 6 metres', explanation: 'Twiga inaweza kufikia urefu wa hadi mita 6, ikifanya kuwa mnyama mrefu zaidi duniani.', explanation_en: 'Giraffes can reach up to 6 metres, making them the tallest animals on earth.', difficulty: 'medium' },
  { id: 'q200', category: 'Wanyama na Hifadhi', question: 'Kiboko (Hippopotamus) huishi wapi Tanzania?', question_en: 'Where do hippos live in Tanzania?', options: ['Mito na maziwa', 'Savanna kavu', 'Misitu ya mvua ya pwani', 'Bahari ya Hindi'], options_en: ['Rivers and lakes', 'Dry savannah', 'Coastal rainforests', 'Indian Ocean'], answer: 'Mito na maziwa', answer_en: 'Rivers and lakes', explanation: 'Kiboko huishi mito na maziwa — maji baridi ni muhimu kudhibiti joto la mwili wake.', explanation_en: 'Hippos live in rivers and lakes — cool water is essential to regulate their body temperature.', difficulty: 'easy' },
  { id: 'q201', category: 'Wanyama na Hifadhi', question: 'Flamingo wengi Tanzania hupatikana ziwa gani?', question_en: 'Large flamingo populations in Tanzania are found at which lake?', options: ['Ziwa Natron', 'Ziwa Victoria', 'Ziwa Tanganyika', 'Ziwa Manyara'], options_en: ['Lake Natron', 'Lake Victoria', 'Lake Tanganyika', 'Lake Manyara'], answer: 'Ziwa Natron', answer_en: 'Lake Natron', explanation: 'Ziwa Natron ni eneo muhimu la kuzaliana kwa flamingo wekundu duniani.', explanation_en: "Lake Natron is one of the world's most important flamingo breeding sites.", difficulty: 'hard' },
  { id: 'q202', category: 'Wanyama na Hifadhi', question: 'Big Five ya wanyama wa Afrika ni ipi?', question_en: "What are Africa's Big Five animals?", options: ['Simba, Ndovu, Nyati, Kifaru, Chui', 'Simba, Twiga, Punda Milia, Nyati, Ndovu', 'Simba, Ndovu, Kiboko, Twiga, Chui', 'Simba, Kifaru, Tembo, Ngo, Duma'], options_en: ['Lion, Elephant, Buffalo, Rhino, Leopard', 'Lion, Giraffe, Zebra, Buffalo, Elephant', 'Lion, Elephant, Hippo, Giraffe, Leopard', 'Lion, Rhino, Elephant, Hyena, Cheetah'], answer: 'Simba, Ndovu, Nyati, Kifaru, Chui', answer_en: 'Lion, Elephant, Buffalo, Rhino, Leopard', explanation: 'Big Five ni: Simba (Lion), Ndovu (Elephant), Nyati (Buffalo), Kifaru (Rhino), Chui (Leopard).', explanation_en: 'The Big Five are: Lion, Elephant, Buffalo, Rhinoceros, and Leopard.', difficulty: 'medium' },
];
